import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANG_KEY = 'lunela_language';

// ─── Dictionnaire de traduction ───────────────────────────────────────────────
// Couverture actuelle : parcours d'authentification (Welcome/Login/Register),
// titres de navigation et menu latéral. Le reste de l'app reste en français —
// extension prévue écran par écran.
export const TRANSLATIONS = {
  fr: {
    // Welcome
    welcome_tagline1: 'Éclairée.',
    welcome_tagline2: 'Épanouie.',
    welcome_tagline3: 'Libre.',
    welcome_subtitle_pre: 'La santé intime et reproductive pour',
    welcome_subtitle_bold: 'toutes et tous',
    profile_feminine_label: 'Féminin',
    profile_feminine_desc: 'Suis ton cycle,\ncomprends ton corps',
    profile_masculine_label: 'Masculin',
    profile_masculine_desc: 'Comprends, soutiens\net grandis',
    profile_health_label: 'Santé',
    profile_health_desc: 'Accompagne tes\npatients avec LUNELA',
    create_account: 'Créer un compte',
    login: 'Se connecter',
    or_continue_with: 'ou continuer avec',
    or: 'ou',
    continue_google: 'Continuer avec Google',
    join_specialist: 'Rejoindre comme spécialiste',
    admin_space: 'Espace admin',
    terms_pre: 'En continuant, vous acceptez nos',
    terms_link: "Conditions d'utilisation",
    credit_pre: 'Pensée par',

    // Login
    login_title: 'Bon retour !',
    login_subtitle: 'Connecte-toi à ton espace LUNELA',
    email_address: 'Adresse email',
    password: 'Mot de passe',
    forgot_password: 'Mot de passe oublié ?',
    no_account_pre: 'Pas encore de compte ? ',
    register_link: "S'inscrire",
    email_invalid: "Format d'email invalide.",
    forgot_title: 'Mot de passe oublié ?',
    forgot_subtitle: 'Indique ton adresse email, tu recevras un lien pour créer un nouveau mot de passe.',
    send_link: 'Envoyer le lien',
    cancel: 'Annuler',
    email_sent_title: 'Email envoyé !',
    back_to_login: 'Retour à la connexion',

    // Register
    register_title: 'Créer un compte',
    register_choose_subtitle: 'Choisis ton profil pour une expérience personnalisée',
    profile_feminine: 'Profil féminin',
    profile_feminine_full_desc: 'Suivi du cycle, journal de symptômes, éducation reproductive et chat avec des spécialistes',
    profile_masculine: 'Profil masculin',
    profile_masculine_full_desc: 'Santé reproductive masculine, comprendre le cycle, quiz éducatifs et mode partenaire',
    health_worker_q: 'Vous êtes un professionnel de santé ?',
    health_worker_link: 'Inscrivez-vous ici',
    already_account_pre: 'Déjà un compte ? ',
    register_form_subtitle: 'Rejoignez la communauté LUNELA',
    first_name: 'Prénom',
    last_name: 'Nom',
    confirm_password: 'Confirmer le mot de passe',
    create_my_account: 'Créer mon compte',

    // Navigation — titres
    nav_cycle: 'Mon Cycle',
    nav_symptoms: 'Mes Symptômes',
    nav_education: 'Éducation',
    nav_quiz: 'Quiz & Badges',
    nav_forum: 'Forum Anonyme',
    nav_chat: 'Chat Spécialiste',
    nav_profile: 'Mon Profil',
    nav_health: 'Ma Santé',
    nav_understand: 'Comprendre le Cycle',
    nav_understand_short: 'Le Cycle',
    nav_partner: 'Ma Partenaire',
    nav_responsibility: 'Responsabilité',
    nav_contraceptives: 'Contraceptifs',
    nav_more: 'Plus',
    logout: 'Se déconnecter',

    // Profil — sélecteur de langue
    appearance_section: 'Apparence',
    dark_mode: 'Mode sombre',
    dark_mode_desc: 'Bêta — disponible sur les écrans principaux.',
    language_section: 'Langue',
    language_desc: "Change la langue de l'interface (bêta, écrans principaux).",

    // Profil — reste de l'écran
    health_profile_title: 'Mon profil santé',
    my_profile_title: 'Mon profil',
    edit: 'Modifier',
    age_group: "Tranche d'âge",
    goals: 'Objectifs',
    personal_notes: 'Notes personnelles',
    not_specified: 'Non renseigné',
    via_provider: 'via',
    quiz_progression: 'Progression Quiz',
    points: 'Points',
    quizzes_done: 'Quiz faits',
    streak: 'Série 🔥',
    my_badges: 'Mes badges',
    obtained: 'Obtenus',
    to_unlock: 'À débloquer',
    no_badge_text: 'Fais ton premier quiz pour gagner un badge !',
    professional_profile: 'Profil professionnel',
    specialty: 'Spécialité',
    status: 'Statut',
    approved: 'Approuvé ✅',
    notifications_section: 'Notifications',
    reminders_tips: 'Rappels & conseils',
    reminders_desc: 'Rappel avant tes règles, période fertile et conseil santé du jour.',
    privacy_section: 'Confidentialité',
    privacy_item1: 'Données chiffrées et privées',
    privacy_item2: 'Chat 100% anonyme',
    privacy_item3: 'Aucun partage avec des tiers',
    privacy_item4: 'Stockage local sécurisé (SQLite)',
    about_section: 'À propos',
    version_label: 'Version',
    app_label: 'Application',
    slogan_label: 'Slogan',
    app_slogan: 'Éclairée. Épanouie. Libre.',
    credit_designed_by: 'Application pensée par',
    logout_confirm_title: 'Déconnexion',
    logout_confirm_msg: 'Voulez-vous vous déconnecter ?',
    edit_profile_modal_title: 'Modifier mon profil',
    my_goals: 'Mes objectifs',
    notes_optional: 'Notes personnelles (optionnel)',
    notes_placeholder: 'Tes notes privées, observations...',
    save: 'Enregistrer',
    age_under_18: '< 18 ans',
    age_18_25: '18-25 ans',
    age_26_35: '26-35 ans',
    age_36_45: '36-45 ans',
    age_over_45: '> 45 ans',
    goal_avoid_pregnancy: 'Éviter une grossesse',
    goal_plan_pregnancy: 'Planifier une grossesse',
    goal_sex_education: 'Éducation sexuelle',
    goal_health_tracking: 'Suivi santé',
    goal_other: 'Autre',
    goal_understand_cycle: 'Comprendre le cycle féminin',
    goal_support_partner: 'Soutenir ma partenaire',
    goal_reproductive_responsibility: 'Responsabilité reproductive',

    // Cycle
    share: 'Partager',
    share_cycle_title: 'Partager mon cycle',
    share_cycle_desc: 'Invite ton partenaire à suivre ton cycle et à mieux te soutenir',
    ignore: 'Ignorer',
    consult_expert_emoji: '👩‍⚕️ Consulter un expert',
    consult_expert: 'Consulter un expert',
    period_title_emoji: '📍 Règles',
    period_already_marked: 'Ce jour ({date}) est déjà marqué comme début de règles.',
    period_start_title: 'Début des règles',
    period_start_confirm: 'Enregistrer le {date} comme début de vos règles ?',
    cancel_action: 'Annuler',
    confirm_action: 'Confirmer',
    saved_check: 'Enregistré ✓',
    period_added_to_tracking: 'Le {date} a été ajouté à votre suivi.',
    error_generic: 'Erreur',
    cycle_length_error: 'La durée du cycle doit être entre 21 et 45 jours.',
    period_length_error: 'La durée des règles doit être entre 2 et 10 jours.',
    future_date_error: 'Impossible de marquer une date future comme début de règles.',
    delete_period_confirm: 'Supprimer cette entrée de règles ({date}) ?',
    period_deleted: 'Entrée supprimée.',
    log_period_today: "Mes règles ont commencé aujourd'hui",
    no_cycle_history_hint: "Aucune règle enregistrée pour l'instant. Utilise le bouton ci-dessus ou touche un jour du calendrier pour commencer ton suivi — ton historique apparaîtra ici.",
    cycle_settings_updated: 'Paramètres du cycle mis à jour.',
    next_period_in: 'Prochaines règles dans',
    days_word: 'jours',
    today_word: "Aujourd'hui",
    in_progress_word: 'En cours',
    ovulation_label: 'Ovulation',
    fertile_window: 'Fenêtre fertile',
    cycle_duration: 'Durée cycle',
    period_duration: 'Durée règles',
    cycle_trend_title: 'Évolution de la durée du cycle',
    my_last_cycles: 'Mes derniers cycles',
    did_you_know: 'Le saviez-vous ?',
    cycle_tip_text: "Un cycle normal dure entre 21 et 35 jours. Appuyez sur n'importe quel jour pour enregistrer le début de vos règles.",
    cycle_settings_title: 'Paramètres du cycle',
    cycle_length_label: 'Durée du cycle (jours)',
    period_length_label: 'Durée des règles (jours)',
    period_start_label: 'Début :',
    period_word_short: 'Règles',

    // Symptoms
    mood_happy: 'Bien',
    mood_neutral: 'Neutre',
    mood_sad: 'Triste',
    mood_anxious: 'Anxieux',
    mood_energetic: 'Énergique',
    my_journal: 'Mon journal',
    edit_label: 'Modifier',
    journal_tab: 'Journal',
    history_tab: 'Historique',
    how_do_you_feel: 'Comment tu te sens ?',
    feeling_today: '{mood}  Tu te sens {label} aujourd\'hui',
    pains_title: 'Douleurs',
    has_pain: 'J\'ai des douleurs',
    no_pain: 'Pas de douleurs',
    intensity_label: 'Intensité',
    pain_mild: 'Légère',
    pain_unbearable: 'Insupportable',
    energy_level: 'Niveau d\'énergie',
    fatigue_label: 'Fatigue',
    fatigue_exhausted: 'Épuisée',
    fatigue_energetic: 'Pleine d\'énergie',
    notes_facultative: 'Notes (facultatif)',
    notes_symptom_placeholder: 'Décris ce que tu ressens, des symptômes particuliers...',
    missing_mood_title: 'Humeur manquante',
    missing_mood_msg: 'Sélectionne ton humeur du jour avant d\'enregistrer.',
    save_error: 'Impossible d\'enregistrer. Réessaie.',
    saved_exclaim: 'Enregistré !',
    update_action: 'Mettre à jour',
    save_action: 'Enregistrer',
    symptom_tip_text: 'Tenir un journal régulier aide à identifier des patterns dans ton cycle et à mieux comprendre ton corps.',
    no_symptom_history: "Aucun symptôme enregistré pour l'instant. Ton historique des 14 derniers jours apparaîtra ici.",
    pain_intensity_short: 'Douleur {n}/10',
    no_pain_short: 'Sans douleur',
    fatigue_short: 'Fatigue {n}/10',

    // ShareCycle
    status_pending: 'En attente',
    status_active: 'Actif',
    status_revoked: 'Révoqué',
    code_label: 'Code',
    created_on: 'Créé le {date}',
    partner_label: 'Partenaire : {name}',
    share_code_action: 'Partager le code',
    revoke_action: 'Révoquer',
    share_join_message: 'Rejoins-moi sur LUNELA ! Mon code de partage de cycle : {code}',
    share_join_title: 'Partage de cycle LUNELA',
    load_shares_error: 'Impossible de charger les partages. Vérifiez votre connexion.',
    existing_link_title: 'Lien existant',
    existing_link_msg: 'Tu as déjà un partage actif ou en attente. Révoque-le avant d\'en créer un nouveau.',
    default_user_name: 'Utilisatrice',
    create_share_error: 'Impossible de créer le partage. Réessaie.',
    revoke_share_title: 'Révoquer le partage',
    revoke_active_msg: 'Ton partenaire ne pourra plus voir ton cycle. Cette action est irréversible.',
    revoke_pending_msg: "Ce code d'invitation sera annulé.",
    revoke_error: 'Révocation impossible. Réessaie.',
    how_it_works: 'Comment ça marche ?',
    share_cycle_explain: 'Génère un code d\'invitation et partage-le avec ton partenaire. Il pourra voir les infos de ton cycle sur son profil Masculin. Tu peux révoquer l\'accès à tout moment.',
    revocable_access: 'Accès révocable',
    limited_info: 'Infos limitées',
    secure_data: 'Données sécurisées',
    generate_invite_code: 'Générer un code d\'invitation',
    current_share: 'Partage actuel',
    no_active_share: 'Aucun partage actif',
    history_label: 'Historique',
    no_share_title: 'Aucun partage',
    no_share_desc: 'Génère un code pour permettre à ton partenaire de voir ton cycle.',

    // Education
    nav_education: 'Éducation',
    education_subtitle: 'Apprends à connaître ton corps',
    no_content_category: 'Aucun contenu dans cette catégorie pour l\'instant.',
    content_validated_note: 'Contenu validé par des professionnels de santé',
    article_educational_note: 'Ces informations sont éducatives. Pour toute question personnelle, consulte un professionnel de santé via le Chat.',

    // Boy Health
    my_health: 'Ma Santé',
    daily_tracking: 'Suivi du jour',
    mood_label: 'Humeur',
    stress_label: 'Stress',
    energy_label: 'Énergie',
    notes_optional_placeholder: 'Notes (facultatif)...',
    trends_7d: 'Tendances (7 derniers jours)',
    specialist_chat: 'Chat Spécialiste',
    specialist_chat_sub: 'Pose tes questions en toute confidentialité',
    my_body: 'Mon corps',
    no_data: 'Aucune donnée',
    health_tip_text: "Enregistre tes données chaque jour pour mieux comprendre l'impact du stress et du sommeil sur ton bien-être.",
    personal_question_note: 'Pour toute question personnelle, consulte un professionnel via le Chat.',

    // UnderstandCycle
    understand_cycle_title: 'Comprendre le Cycle',
    understand_cycle_sub: 'Pour mieux soutenir et être là',
    understand_cycle_intro: "Comprendre le cycle menstruel te permet d'être un meilleur partenaire, frère ou ami. Appuie sur chaque phase pour en savoir plus.",
    four_phases: 'Les 4 phases',
    test_knowledge: 'Teste tes connaissances !',
    quiz_badges_sub: 'Réponds au quiz et gagne des badges',
    myths_realities: 'Mythes & Réalités',
    myth_label: 'MYTHE',
    reality_label: 'RÉALITÉ',
    go_further: 'Pour aller plus loin',
    understand_cycle_tip: "Chaque femme vit son cycle différemment. Le dialogue et l'écoute sont les meilleures façons de comprendre ce que ressent ta partenaire.",

    // Quiz
    points_label: 'Points',
    quizzes_done_label: 'Quiz faits',
    streak_label: 'Série 🔥',
    badges_count: 'Badges : {n} / {total}',
    quiz_tab: 'Quiz',
    badges_tab: 'Badges',
    choose_category: 'Choisir une catégorie',
    your_badges: 'Tes badges',
    questions_count: '{n} questions',
    completed_label: 'Terminé',
    validate_action: 'Valider',
    see_results: 'Voir les résultats',
    next_question: 'Question suivante',
    perfect_score: 'Score parfait !',
    good_job: 'Beau travail !',
    keep_learning: "Continue d'apprendre !",
    new_badges_title: '🏅 Nouveaux badges !',
    replay_action: 'Rejouer',
    back_to_quizzes: 'Retour aux quiz',

    // Partner
    phase_menstruation: 'Menstruation',
    phase_follicular: 'Phase folliculaire',
    phase_ovulation: 'Ovulation',
    phase_luteal: 'Phase lutéale',
    phase_tip_menstruation: 'Phase des règles. Elle peut ressentir des crampes ou de la fatigue.',
    phase_tip_follicular: 'Énergie en hausse. Bon moment pour des activités ensemble.',
    phase_tip_ovulation: 'Période fertile. Humeur généralement positive.',
    phase_tip_luteal: 'Possible SPM en fin de phase. Sois attentif à son bien-être.',
    weekday_mon: 'Lu', weekday_tue: 'Ma', weekday_wed: 'Me', weekday_thu: 'Je',
    weekday_fri: 'Ve', weekday_sat: 'Sa', weekday_sun: 'Di',
    period_legend: 'Règles',
    fertile_legend: 'Fertile',
    cycle_legend: 'Cycle',
    partner_tip1: 'Demande comment elle se sent sans attendre une réponse précise.',
    partner_tip2: 'Un thé chaud ou une bouillotte peut soulager les crampes.',
    partner_tip3: "Une courte promenade ensemble peut améliorer l'humeur pendant le SPM.",
    partner_tip4: 'Proposer un film ou une activité calme pendant les règles est toujours apprécié.',
    partner_tip5: "Sois patient : les variations d'humeur sont hormonales, pas personnelles.",
    partner_mode_title: 'Mode Partenaire',
    partner_mode_sub: 'Connecte-toi avec ta partenaire pour mieux comprendre son cycle et être là pour elle.',
    enter_partner_code: 'Entre le code de ta partenaire',
    enter_partner_code_sub: 'Elle génère ce code depuis son application LUNELA → Mon Cycle → 👥',
    code_placeholder: 'EX : AB3X7K',
    code_too_short: 'Code trop court.',
    code_not_found: 'Code introuvable ou déjà utilisé.',
    cant_use_own_code: 'Tu ne peux pas utiliser ton propre code.',
    network_error_retry: 'Erreur réseau. Réessaie.',
    connect_action: 'Se connecter',
    why_use_mode: 'Pourquoi utiliser ce mode ?',
    why_tip1: 'Voir son cycle et anticiper les périodes difficiles',
    why_tip2: 'Recevoir des conseils personnalisés selon sa phase',
    why_tip3: 'Mieux comprendre pour mieux soutenir',
    connected_label: 'Connecté',
    unlink_action: 'Délier',
    unlink_title: 'Délier la partenaire',
    unlink_msg: "Tu n'auras plus accès à son cycle. Confirmer ?",
    cycle_day_label: 'Jour {n} du cycle',
    next_period_label: 'Prochaines règles',
    empathy_tip_of_day: "Conseil d'empathie du jour",
    partner_cycle_calendar: 'Calendrier de son cycle',
    recent_history: 'Historique récent',
    period_from_date: 'Règles du {date}',
    duration_days: 'Durée : {n} jours',
    partner_no_data: "Ta partenaire n'a pas encore enregistré de cycle. Reviens plus tard.",
    recent_symptoms_14d: '💊 Symptômes récents (14 jours)',
    next_tip: 'Conseil suivant',
    close_action: 'Fermer',
    default_partner_name: 'Ta partenaire',

    // Responsibility (UI chrome only — long-form content stays French)
    tab_contraception: 'Contraception',
    tab_consent: 'Consentement',
    tab_planning: 'Planning',
    contra_intro_title: 'La contraception : une responsabilité partagée',
    contra_intro_text: "Connaître toutes les méthodes te permet d'avoir une conversation ouverte et de prendre des décisions ensemble.",
    advantages_label: '✅ Avantages',
    attention_points_label: "⚠️ Points d'attention",
    how_it_works_label: '📋 Comment ça marche',
    no_ist_protection_warning: "Cette méthode ne protège pas contre les IST/VIH. Utilise un préservatif en complément si tu n'es pas dans une relation exclusive et testée.",
    important_reminder_label: 'Rappel important :',
    important_reminder_text: 'Seul le préservatif protège simultanément contre les grossesses non désirées et les IST. La "double protection" (préservatif + autre méthode) est la combinaison la plus sûre.',
    consent_hero_title: 'Le consentement éclairé',
    consent_hero_sub: "Comprendre et respecter le consentement est la base de toute relation saine. Ce n'est pas optionnel, c'est fondamental.",
    fries_principles_title: 'Les 5 principes FREES',
    red_flags_title: 'Comportements à ne jamais adopter',
    how_to_talk_consent: 'Comment parler de consentement ?',
    consent_note_text: "Poser ces questions n'est pas maladroit — c'est une marque de respect et de maturité qui renforce la confiance dans la relation.",
    planning_hero_title: 'Planification familiale',
    planning_hero_sub: "La décision d'avoir un enfant est l'une des plus importantes de la vie. Elle se prend à deux, avec communication et préparation.",
    planning_topics_title: 'Sujets essentiels à aborder ensemble',
    ist_screening_label: 'Dépistage IST :',
    ist_screening_text: "Avant d'arrêter la contraception barrière, il est recommandé que les deux partenaires fassent un bilan IST complet. C'est un acte de respect mutuel, pas de méfiance.",
    useful_resources_title: 'Ressources utiles',

    // Onboarding
    onboard_title_1: 'Bienvenue sur\nLUNELA',
    onboard_sub_1: 'Votre compagnon de santé intime et reproductive. Conçu avec amour pour toutes et tous.',
    onboard_title_2: 'Suivez votre\ncycle',
    onboard_sub_2: 'Enregistrez vos règles, visualisez votre cycle sur un calendrier coloré, et anticipez chaque phase.',
    onboard_title_3: 'Chat avec des\nspécialistes',
    onboard_sub_3: 'Posez vos questions en toute confidentialité à des professionnels de santé approuvés. Votre identité reste anonyme.',
    onboard_title_4: 'Vos données,\nvos règles',
    onboard_sub_4: 'Tout est chiffré et sécurisé. Vous choisissez ce que vous partagez, et avec qui.',
    start_action: 'Commencer',
    next_action: 'Suivant',
    skip_action: 'Passer',

    // SurveyGate
    gender_female: 'Femme',
    gender_male: 'Homme',
    gender_other: 'Autre/Non précisé',
    mandatory_label: 'Obligatoire',
    select_answer_required: 'Veuillez sélectionner une réponse.',
    select_gender_required: 'Veuillez indiquer votre sexe.',
    gender_not_specified: 'Non précisé',
    save_response_error: "Impossible d'enregistrer votre réponse. Vérifie ta connexion.",
    mandatory_survey_badge: 'SONDAGE OBLIGATOIRE',
    survey_intro_text: 'Veuillez répondre à ce sondage pour continuer à utiliser LUNELA.',
    your_answer_label: 'Votre réponse',
    your_gender_label: 'Votre sexe',
    submit_answer: 'Valider ma réponse',
    survey_anon_note: 'Votre réponse est anonyme et confidentielle.',

    // Contraceptives
    daily_reminder_title: 'Rappel quotidien',
    daily_reminder_sub: 'Recevoir un rappel chaque jour',
    reminder_time_label: 'Heure du rappel :',
    contraceptive_reminder_title: '💊 Rappel contraceptif',
    contraceptive_reminder_body: "N'oubliez pas de prendre votre contraceptif aujourd'hui.",
    contraceptives_title: 'Contraceptifs & Protection',
    contraceptives_sub: 'Guide complet des méthodes contraceptives et de protection',
    no_items_category: 'Aucun élément dans cette catégorie',
    contraceptives_disclaimer: 'Ces informations sont éducatives. Consultez un professionnel de santé pour un choix adapté.',
    efficacy_label: 'Efficacité',
    duration_label: 'Durée',
    advantages_short: '✅ Avantages',
    disadvantages_short: '⚠️ Inconvénients',

    // Chat
    anonymous_label: 'Anonyme',
    message_not_sent: 'Message non envoyé. Vérifiez votre connexion.',
    you_appear_as: 'Vous apparaissez comme : ',
    available_specialists: 'Spécialistes disponibles',
    no_specialist_available: 'Aucun spécialiste disponible\npour le moment',
    online_label: 'En ligne',
    offline_label: 'Hors ligne',
    health_specialist_default: 'Spécialiste santé',
    you_prefix: 'Vous : ',
    confidentiality_guaranteed: 'Confidentialité garantie',
    confidentiality_text: "Votre identité réelle n'est jamais révélée aux spécialistes.",
    start_conversation: 'Démarrez la conversation.\nVous êtes anonyme.',
    message_placeholder: 'Votre message...',
    new_patient_message: '💬 Nouveau message patient',
    chat_screen_sub: 'Discutez en toute confidentialité',

    // Forum
    specialist_professional_label: 'Professionnel de santé',
    just_now: "À l'instant",
    minutes_ago: 'Il y a {n} min',
    hours_ago: 'Il y a {n}h',
    thanks_label: 'Merci',
    report_transmitted: 'Ton signalement a été transmis à la modération.',
    report_send_error: "Impossible d'envoyer le signalement.",
    report_content_title: 'Signaler ce contenu',
    report_content_why: 'Pourquoi signales-tu ce contenu ?',
    send_report_action: 'Envoyer le signalement',
    discussion_default: 'Discussion',
    reply_send_error: "Impossible d'envoyer la réponse.",
    be_first_to_reply: 'Soyez le premier à répondre',
    reply_placeholder: 'Votre réponse...',
    forum_title: 'Forum Anonyme',
    post_action: 'Poster',
    specialist_reply_note: "Tes réponses sont identifiées comme venant d'un professionnel de santé.",
    no_discussion_yet: "Aucune discussion pour l'instant",
    publish_post_error: 'Impossible de publier.',
    new_discussion_title: 'Nouvelle discussion',
    question_title_placeholder: 'Titre de votre question...',
    describe_situation_placeholder: 'Décrivez votre situation...',
    publish_anonymously: 'Publier anonymement',

    // VerifyEmail
    not_yet_verified_title: 'Pas encore vérifié',
    not_yet_verified_msg: "Ouvrez votre boîte mail, trouvez l'email de LUNELA et cliquez sur le lien de confirmation. Revenez ensuite ici.",
    network_error_title: 'Erreur réseau',
    network_error_msg: 'Vérifiez votre connexion internet.',
    email_sent_title: 'Email envoyé',
    email_sent_msg: 'Un nouvel email de vérification a été envoyé à {email}',
    resend_email_error: "Impossible d'envoyer l'email. Réessayez plus tard.",
    verify_email_title: 'Vérifiez votre email',
    verify_email_sub: 'Un lien de confirmation a été envoyé à votre adresse email.',
    verify_step1: 'Ouvrez votre boîte mail',
    verify_step2: "Trouvez l'email de LUNELA",
    verify_step3: 'Cliquez sur le lien de confirmation',
    verify_step4: 'Revenez ici et appuyez sur le bouton ci-dessous',
    confirmed_email_action: "J'ai confirmé mon email",
    resend_in_seconds: 'Renvoyer dans {n}s',
    resend_email_action: "Renvoyer l'email",
    spam_notice: 'Pensez à vérifier vos spams / courriers indésirables',
    logout_action: 'Se déconnecter',

    // PendingApproval
    pending_request_title: 'Demande en attente',
    pending_admin_sub: 'Votre demande de compte administrateur est en cours de validation par un administrateur existant.',
    pending_specialist_sub: "Votre demande de compte spécialiste est en cours de validation par notre équipe d'administration.",
    status_label: 'Statut :',
    pending_status: 'En attente',
    check_status_action: 'Vérifier le statut',

    // AdminRegister / SpecialistRegister
    fill_all_fields: 'Veuillez remplir tous les champs.',
    passwords_mismatch: 'Les mots de passe ne correspondent pas.',
    password_too_short: 'Mot de passe trop court (min. 6 caractères).',
    admin_account_title: 'Compte Administrateur',
    first_admin_note: 'Premier administrateur — Compte approuvé automatiquement',
    admin_pending_note: 'Votre compte sera validé par un administrateur existant',
    full_name_label: 'Nom complet',
    email_address_label: 'Adresse email',
    password_label: 'Mot de passe',
    confirm_password_label: 'Confirmer le mot de passe',
    min_6_chars_placeholder: 'Minimum 6 caractères',
    retype_password_placeholder: 'Retapez le mot de passe',
    create_account_action: 'Créer le compte',
    fill_required_fields: 'Veuillez remplir tous les champs obligatoires.',
    specialist_account_title: 'Compte Spécialiste',
    specialist_pending_note: "Votre demande sera examinée et approuvée par notre équipe d'administration.",
    full_name_required: 'Nom complet *',
    email_required: 'Email *',
    speciality_required: 'Spécialité *',
    credentials_label: "Diplômes / Numéro d'ordre *",
    credentials_placeholder: 'Ex: Doctorat en médecine - N° Ordre 12345',
    institution_label: 'Établissement / Institution',
    institution_placeholder: 'Hôpital / Clinique / Cabinet',
    professional_phone_label: 'Téléphone professionnel',
    password_required: 'Mot de passe *',
    confirm_password_required: 'Confirmer le mot de passe *',
    submit_request_action: 'Soumettre ma demande',

    // AdminDashboard
    live_updated: 'Temps réel · MàJ {time}',
    greeting_hello: 'Bonjour 👋',
    admin_default_name: 'Administrateur',
    admin_role_badge: 'Administrateur LUNELA',
    pending_specialist_approval: "⚠️ {n} en attente d'approbation",
    approved_count: '{n} approuvé(s)',
    active_of_total_surveys: '{active} actif(s) · {total} au total',
    pending_count: '⚠️ {n} en attente',
    active_count: '{n} actif(s)',
    manage_contraceptive_methods: 'Gérer les méthodes de contraception',
    pending_reports_count: '⚠️ {n} signalement(s) en attente',
    no_pending_reports: 'Aucun signalement en attente',
    elements_pending_action: '{n} élément{s} en attente d\'action',
    overview_title: "Vue d'ensemble",
    users_group_label: '👥 Utilisateurs',
    total_label: 'Total',
    women_label: 'Femmes',
    men_label: 'Hommes',
    specialists_group_label: '🩺 Spécialistes',
    approved_label: 'Approuvés',
    pending_label: 'En attente',
    blocked_label: 'Bloqués',
    platform_group_label: '📊 Plateforme',
    active_surveys_label: 'Sondages actifs',
    total_surveys_label: 'Total sondages',
    admins_pending_label: 'Admins attente',
    analytics_title: 'Analytiques',
    users_distribution: 'Répartition des utilisateurs',
    total_word: 'total',
    others_label: 'Autres',
    specialists_status: 'Statut des spécialistes',
    platform_label: 'Plateforme',
    active_admins_label: 'Admins actifs',
    approved_specialists_label: 'Spécialistes approuvés',
    management_title: 'Gestion',
    create_new_survey: 'Créer un nouveau sondage',
    view_survey_reports: 'Voir les rapports de sondages',
    specialists_label: 'Spécialistes',
    surveys_label: 'Sondages',
    administrators_label: 'Administrateurs',
    contraceptives_label: 'Contraceptifs',
    forum_moderation_label: 'Modération Forum',

    // SpecialistApproval
    specialist_management_title: 'Gestion Spécialistes',
    action_approve: 'approuver',
    action_block: 'bloquer',
    action_reset_pending: 'remettre en attente',
    confirm_title: 'Confirmer',
    confirm_action_person: 'Voulez-vous {action} Dr. {name} ?',
    success_title: '✅ Succès',
    status_updated: 'Statut mis à jour : {status}',
    update_failed: 'Mise à jour échouée : {error}',
    load_error_prefix: 'Erreur : {error}',
    specialists_load_error: 'Impossible de charger les spécialistes.\n{error}',
    loading_impossible: 'Chargement impossible',
    retry_action: 'Réessayer',
    no_specialists_category: 'Aucun spécialiste dans cette catégorie',
    pull_to_refresh_hint: 'Tire vers le bas pour actualiser',
    approve_action: 'Approuver',
    reject_action: 'Refuser',
    block_action: 'Bloquer',
    unblock_action: 'Débloquer',

    // AdminManagement
    approve_or_reject_admin: '{action} le compte admin de {name} ?',
    first_admin_auto_note: 'Le premier administrateur est créé automatiquement. Les suivants nécessitent votre approbation.',
    no_admin_category: 'Aucun administrateur dans cette catégorie',
    first_admin_badge: '⭐ Premier Admin',
    you_label: '👑 Vous',

    // ForumModeration
    action_impossible: 'Action impossible.',
    delete_content_title: 'Supprimer ce contenu',
    delete_reply_msg: 'Cette réponse sera définitivement supprimée du forum.',
    delete_discussion_msg: 'Cette discussion et toutes ses réponses seront définitivement supprimées.',
    delete_action: 'Supprimer',
    delete_impossible: 'Suppression impossible.',
    reported_reply: 'Réponse signalée',
    reported_discussion: 'Discussion signalée',
    empty_content_label: '(contenu vide)',
    forum_clean_note: 'Le forum est propre pour le moment.',

    // ContraceptivesManager
    delete_confirm_name: 'Supprimer "{name}" ?',
    delete_failed: 'Suppression échouée.',
    name_required: 'Le nom est obligatoire.',
    save_failed: 'Sauvegarde échouée.',
    no_item: 'Aucun élément',
    edit_action: 'Modifier',
    add_item_action: 'Ajouter un élément',
    change_action: 'Changer',
    color_label: 'Couleur',
    name_required_label: 'Nom *',
    category_label: 'Catégorie',
    efficacy_field_label: 'Efficacité',
    duration_field_label: 'Durée',
    description_label: 'Description',
    description_placeholder: 'Description de la méthode...',
    advantages_max3: 'Avantages (3 max)',
    advantage_n: 'Avantage {n}',
    disadvantages_max3: 'Inconvénients (3 max)',
    disadvantage_n: 'Inconvénient {n}',
    choose_emoji: 'Choisir un emoji',

    // SurveyManager
    disable_mandatory_confirm: "Désactiver l'obligation de réponse ?",
    make_mandatory_confirm: "⚠️ Rendre ce sondage OBLIGATOIRE ? Les utilisatrices devront y répondre avant d'utiliser l'app.",
    delete_survey_confirm: 'Supprimer définitivement "{title}" ?',
    create_action: 'Créer',
    no_survey_created: 'Aucun sondage créé',
    create_first_survey: 'Créer le premier sondage',
    mandatory_badge: 'OBLIGATOIRE',
    closed_badge: 'FERMÉ',
    options_count: '{n} options',
    responses_count: '{n} réponses',
    public_label: 'Public',
    private_label: 'Privé',
    active_toggle: '● Actif',
    inactive_toggle: '○ Inactif',
    mandatory_toggle: 'Obligatoire',
    optional_toggle: '○ Facultatif',
    report_label: 'Rapport',

    // CreateSurvey
    max_8_options: 'Maximum 8 options',
    min_2_options: 'Minimum 2 options',
    enter_title_error: 'Veuillez saisir un titre.',
    enter_question_error: 'Veuillez saisir la question.',
    min_2_options_error: 'Minimum 2 options de réponse.',
    survey_created_title: '✅ Sondage créé',
    survey_created_mandatory_msg: 'Le sondage est obligatoire — les utilisatrices devront y répondre.',
    survey_created_active_msg: 'Le sondage est maintenant actif.',
    create_survey_error: 'Impossible de créer le sondage.',
    new_survey_title: 'Nouveau Sondage',
    survey_title_label: 'Titre du sondage *',
    survey_title_placeholder: 'Ex: Satisfaction des services LUNELA',
    question_asked_label: 'Question posée *',
    question_placeholder: 'Posez votre question ici...',
    response_options_label: 'Options de réponse *',
    option_n: 'Option {letter}',
    add_option_action: '+ Ajouter une option',
    settings_title: '⚙️ Paramètres',
    mandatory_survey_label: '⚡ Sondage obligatoire',
    mandatory_survey_desc: 'Les utilisatrices doivent répondre pour continuer',
    public_survey_label: '🌍 Sondage public',
    public_survey_desc: 'Visible par toutes les utilisatrices',
    ask_gender_label: '👤 Demander le sexe',
    ask_gender_desc: 'Chaque répondant renseigne son sexe',
    mandatory_survey_warning: "⚡ Ce sondage sera affiché à toutes les utilisatrices actives et bloquera l'accès à l'app jusqu'à réponse.",
    creating_ellipsis: 'Création...',
    launch_survey_action: '🚀 Lancer le sondage',

    // SurveyReport
    survey_report_title: 'Rapport Sondage',
    total_responses: '👥 {n} réponses',
    results_by_answer: 'Résultats par réponse',
    gender_breakdown_title: 'Répartition par sexe',
    no_response_yet: "Aucune réponse pour l'instant",
    export_report_action: 'Exporter le rapport',
    report_survey_prefix: 'RAPPORT SONDAGE LUNELA',
    report_title_field: 'Titre',
    report_question_field: 'Question',
    report_total_responses_field: 'Total réponses',
    report_by_answer: 'PAR RÉPONSE:',
    report_by_gender: 'PAR SEXE:',
    report_share_title: 'Rapport - {title}',
    not_specified_short: 'Non précisé',

    // SpecialistDashboard
    patient_default: 'Patient·e',
    dossier_label: 'Dossier',
    no_message_yet: "Aucun message pour l'instant",
    professional_response_placeholder: 'Votre réponse professionnelle...',
    message_not_sent_short: 'Message non envoyé.',
    new_reply_notification: '💬 Réponse de {name}',
    default_specialist: 'Spécialiste',
    default_specialist_short: 'votre spécialiste',
    conversations_title: 'Conversations',
    urgent_count_label: '{n} urgent{s}',
    all_count: 'Tous ({n})',
    urgent_only_count: 'Urgents ({n})',
    no_urgent_conv: 'Aucune conversation urgente',
    no_conversation: 'Aucune conversation',
    all_conv_uptodate: 'Toutes les conversations sont à jour ✅',
    patients_appear_here: 'Les patients qui vous contactent apparaîtront ici',
    urgent_flag: 'URGENT',
    start_conv_placeholder: 'Démarrer la conversation...',
    stats_title: 'Statistiques',
    kpi_conversations: 'Conversations',
    kpi_messages_received: 'Messages reçus',
    kpi_unread: 'Non lus',
    kpi_response_rate: 'Taux réponse',
    kpi_avg_msgs: 'Moy. msgs/conv',
    kpi_answered_conv: 'Conv. répondues',
    activity_7d_title: 'Activité — 7 derniers jours',
    no_activity_recorded: 'Aucune activité enregistrée',
    patient_distribution: 'Répartition des patients',
    patients_word: 'patients',
    exchange_quality: 'Qualité des échanges',
    total_conv_short: 'Conv. total',
    answered_short: 'Répondues',
    unread_short: 'Non lus',
    avg_msgs_short: 'Moy. msgs',
    professional_profile: 'Profil professionnel',
    speciality_field: 'Spécialité',
    institution_field: 'Institution',
    phone_field: 'Téléphone',
    diplomas_field: 'Diplômes',
    status_field: 'Statut',
    approved_check: 'Approuvé ✅',
    professional_resources: 'Ressources professionnelles',
    greeting_hello_comma: 'Bonjour,',
    urgent_conversations_count: '{n} conversation{s} urgente{s2}',
    messages_awaiting_reply: '{n} message{s} en attente de réponse',
    conversations_stat: 'Conversations',
    unread_stat: 'Non lus',
    messages_stat: 'Messages',
    conversations_count_label: '{n} patient{s}',
    none_label: 'Aucune',
    overview_label: "Vue d'ensemble",
    resources_sub: 'Protocoles, outils, formations',
    anonymous_forum_label: 'Forum Anonyme',
    follow_exchanges_sub: 'Suivre les échanges et répondre',
    priority_treatment: 'À traiter en priorité',
    recent_label: 'Récentes',
    profile_female_label: 'Profil féminin',
    profile_male_label: 'Profil masculin',
    health_worker_label: 'Personnel de santé',
    resources_label: 'Ressources',

    // ResourcesScreen
    cat_all: 'Tout',
    cat_protocols: 'Protocoles',
    cat_guidelines: 'Guidelines',
    cat_articles: 'Articles',
    cat_tools: 'Outils',
    cat_formations: 'Formations',
    cat_contacts: 'Contacts',
    link_label: 'Lien',
    added_by: 'Ajouté par {name}',
    open_link_error: "Impossible d'ouvrir ce lien.",
    keywords_label: 'Mots-clés',
    access_label: 'Accès',
    call_number: 'Appeler {number}',
    open_link_action: 'Ouvrir le lien',
    source_label: 'Source : {source}',
    lunela_base: 'Base LUNELA',
    required_fields_title: 'Champs requis',
    required_fields_msg: 'Le titre et la description sont obligatoires.',
    save_resource_error: 'Impossible d\'enregistrer. Vérifiez votre connexion.',
    add_resource_title: 'Ajouter une ressource',
    publish_action: 'Publier',
    title_required_label: 'Titre *',
    title_placeholder: 'Ex : Protocole IST – conduite à tenir',
    description_required_label: 'Description *',
    describe_resource_placeholder: 'Décrivez la ressource en détail...',
    url_optional_label: 'Lien URL (optionnel)',
    tags_label: 'Tags (séparés par des virgules)',
    resource_visibility_note: 'La ressource sera visible par tous les spécialistes connectés à LUNELA après publication.',
    search_resource_placeholder: 'Rechercher une ressource...',
    resource_count: '{n} ressource{s}',
    no_result_title: 'Aucun résultat',
    no_result_search: 'Aucune ressource ne correspond à "{search}"',
    no_result_category: 'Aucune ressource dans cette catégorie.',
    add_first_resource: 'Ajouter la première ressource',
    add_action: 'Ajouter',

    // PatientDataSheet
    most_recent_label: 'Plus récent',
    patient_record_title: 'Dossier de suivi',
    symptoms_tab: 'Symptômes',
    cycles_tab: 'Cycles',
    loading_record: 'Chargement du dossier...',
    born_on: 'Né(e) le {date}',
    cycle_approx: 'Cycle ~{n}j',
    symptoms_14d_title: '📋 Symptômes — 14 derniers jours',
    no_symptom_14d: 'Aucun symptôme enregistré sur les 14 derniers jours.',
    last_5_cycles_title: '🌙 5 derniers cycles',
    no_cycle_recorded: 'Aucun cycle enregistré.',
    avg_duration_label: 'Durée moy.',
    cycles_recorded_label: 'Cycles enreg.',
    default_patient_label: 'Patient',

    // QuizManager
    quiz_manager_title: 'Gestion des Quiz',
    add_question_action: 'Ajouter une question',
    question_text_label: 'Question *',
    question_text_placeholder: 'Ex : Combien de jours dure un cycle ?',
    option_n_label: 'Option {n}',
    correct_answer_label: 'Bonne réponse',
    explanation_label: 'Explication',
    explanation_placeholder: 'Explique la réponse correcte...',
    topic_label: 'Catégorie',
    question_required: 'La question et les 4 options sont obligatoires.',
    select_correct_answer: 'Sélectionne la bonne réponse.',
    no_question: 'Aucune question',
    delete_confirm_question: 'Supprimer cette question ?',
    tap_option_to_mark_correct: 'Touche une option pour la marquer comme la bonne réponse.',
    manage_quiz_questions: 'Gérer les questions du quiz',

    // EducationManager
    education_manager_title: 'Gestion du Contenu Éducatif',
    manage_education_content: 'Gérer les articles éducatifs',
    add_article_action: 'Ajouter un article',
    article_title_label: 'Titre *',
    article_title_placeholder: 'Ex : Les 4 phases du cycle menstruel',
    article_body_label: 'Contenu *',
    article_body_placeholder: "Rédige le contenu de l'article...",
    target_profile_label: 'Public visé',
    article_required: 'Le titre et le contenu sont obligatoires.',
    no_article: 'Aucun article',
    delete_confirm_article: 'Supprimer cet article ?',

    // Compte double-profil (fille/garçon + spécialiste)
    nav_become_specialist: 'Devenir spécialiste',
    nav_specialist_pending: 'Candidature en cours',
    nav_specialist_space: 'Espace spécialiste',
    become_specialist_intro: 'Complétez ce formulaire pour soumettre votre candidature. Un administrateur validera votre profil professionnel.',
    specialist_application_pending_title: "Candidature en cours d'examen",
    specialist_application_pending_sub: "Votre candidature de spécialiste est en cours d'examen par un administrateur. Vous serez notifié·e dès son approbation.",
    application_submitted_title: 'Candidature envoyée',
    application_submitted_msg: 'Votre candidature a bien été transmise.',
  },
  en: {
    // Welcome
    welcome_tagline1: 'Enlightened.',
    welcome_tagline2: 'Fulfilled.',
    welcome_tagline3: 'Free.',
    welcome_subtitle_pre: 'Intimate and reproductive health for',
    welcome_subtitle_bold: 'everyone',
    profile_feminine_label: 'Feminine',
    profile_feminine_desc: 'Track your cycle,\nunderstand your body',
    profile_masculine_label: 'Masculine',
    profile_masculine_desc: 'Understand, support\nand grow',
    profile_health_label: 'Health',
    profile_health_desc: 'Support your\npatients with LUNELA',
    create_account: 'Create an account',
    login: 'Log in',
    or_continue_with: 'or continue with',
    or: 'or',
    continue_google: 'Continue with Google',
    join_specialist: 'Join as a specialist',
    admin_space: 'Admin area',
    terms_pre: 'By continuing, you accept our',
    terms_link: 'Terms of use',
    credit_pre: 'Designed by',

    // Login
    login_title: 'Welcome back!',
    login_subtitle: 'Log in to your LUNELA space',
    email_address: 'Email address',
    password: 'Password',
    forgot_password: 'Forgot password?',
    no_account_pre: "Don't have an account? ",
    register_link: 'Sign up',
    email_invalid: 'Invalid email format.',
    forgot_title: 'Forgot password?',
    forgot_subtitle: "Enter your email address, you'll receive a link to create a new password.",
    send_link: 'Send link',
    cancel: 'Cancel',
    email_sent_title: 'Email sent!',
    back_to_login: 'Back to login',

    // Register
    register_title: 'Create an account',
    register_choose_subtitle: 'Choose your profile for a personalized experience',
    profile_feminine: 'Feminine profile',
    profile_feminine_full_desc: 'Cycle tracking, symptom journal, reproductive education and chat with specialists',
    profile_masculine: 'Masculine profile',
    profile_masculine_full_desc: 'Male reproductive health, understanding the cycle, educational quizzes and partner mode',
    health_worker_q: 'Are you a health professional?',
    health_worker_link: 'Register here',
    already_account_pre: 'Already have an account? ',
    register_form_subtitle: 'Join the LUNELA community',
    first_name: 'First name',
    last_name: 'Last name',
    confirm_password: 'Confirm password',
    create_my_account: 'Create my account',

    // Navigation — titles
    nav_cycle: 'My Cycle',
    nav_symptoms: 'My Symptoms',
    nav_education: 'Education',
    nav_quiz: 'Quiz & Badges',
    nav_forum: 'Anonymous Forum',
    nav_chat: 'Specialist Chat',
    nav_profile: 'My Profile',
    nav_health: 'My Health',
    nav_understand: 'Understand the Cycle',
    nav_understand_short: 'The Cycle',
    nav_partner: 'My Partner',
    nav_responsibility: 'Responsibility',
    nav_contraceptives: 'Contraceptives',
    nav_more: 'More',
    logout: 'Log out',

    // Profile — language selector
    appearance_section: 'Appearance',
    dark_mode: 'Dark mode',
    dark_mode_desc: 'Beta — available on the main screens.',
    language_section: 'Language',
    language_desc: 'Change the interface language (beta, main screens).',

    // Profile — rest of the screen
    health_profile_title: 'My health profile',
    my_profile_title: 'My profile',
    edit: 'Edit',
    age_group: 'Age group',
    goals: 'Goals',
    personal_notes: 'Personal notes',
    not_specified: 'Not specified',
    via_provider: 'via',
    quiz_progression: 'Quiz progress',
    points: 'Points',
    quizzes_done: 'Quizzes done',
    streak: 'Streak 🔥',
    my_badges: 'My badges',
    obtained: 'Obtained',
    to_unlock: 'To unlock',
    no_badge_text: 'Take your first quiz to earn a badge!',
    professional_profile: 'Professional profile',
    specialty: 'Specialty',
    status: 'Status',
    approved: 'Approved ✅',
    notifications_section: 'Notifications',
    reminders_tips: 'Reminders & tips',
    reminders_desc: 'Reminder before your period, fertile window and daily health tip.',
    privacy_section: 'Privacy',
    privacy_item1: 'Encrypted and private data',
    privacy_item2: '100% anonymous chat',
    privacy_item3: 'No sharing with third parties',
    privacy_item4: 'Secure local storage (SQLite)',
    about_section: 'About',
    version_label: 'Version',
    app_label: 'Application',
    slogan_label: 'Slogan',
    app_slogan: 'Enlightened. Fulfilled. Free.',
    credit_designed_by: 'Application designed by',
    logout_confirm_title: 'Log out',
    logout_confirm_msg: 'Do you want to log out?',
    edit_profile_modal_title: 'Edit my profile',
    my_goals: 'My goals',
    notes_optional: 'Personal notes (optional)',
    notes_placeholder: 'Your private notes, observations...',
    save: 'Save',
    age_under_18: '< 18 years',
    age_18_25: '18-25 years',
    age_26_35: '26-35 years',
    age_36_45: '36-45 years',
    age_over_45: '> 45 years',
    goal_avoid_pregnancy: 'Avoid pregnancy',
    goal_plan_pregnancy: 'Plan a pregnancy',
    goal_sex_education: 'Sex education',
    goal_health_tracking: 'Health tracking',
    goal_other: 'Other',
    goal_understand_cycle: 'Understand the female cycle',
    goal_support_partner: 'Support my partner',
    goal_reproductive_responsibility: 'Reproductive responsibility',

    // Cycle
    share: 'Share',
    share_cycle_title: 'Share my cycle',
    share_cycle_desc: 'Invite your partner to follow your cycle and better support you',
    ignore: 'Ignore',
    consult_expert_emoji: '👩‍⚕️ Consult an expert',
    consult_expert: 'Consult an expert',
    period_title_emoji: '📍 Period',
    period_already_marked: 'This day ({date}) is already marked as the start of your period.',
    period_start_title: 'Start of period',
    period_start_confirm: 'Save {date} as the start of your period?',
    cancel_action: 'Cancel',
    confirm_action: 'Confirm',
    saved_check: 'Saved ✓',
    period_added_to_tracking: '{date} was added to your tracking.',
    error_generic: 'Error',
    cycle_length_error: 'Cycle length must be between 21 and 45 days.',
    period_length_error: 'Period length must be between 2 and 10 days.',
    future_date_error: 'You cannot mark a future date as the start of your period.',
    delete_period_confirm: 'Delete this period entry ({date})?',
    period_deleted: 'Entry deleted.',
    log_period_today: 'My period started today',
    no_cycle_history_hint: 'No period logged yet. Use the button above or tap a day on the calendar to start tracking — your history will appear here.',
    cycle_settings_updated: 'Cycle settings updated.',
    next_period_in: 'Next period in',
    days_word: 'days',
    today_word: 'Today',
    in_progress_word: 'Ongoing',
    ovulation_label: 'Ovulation',
    fertile_window: 'Fertile window',
    cycle_duration: 'Cycle length',
    period_duration: 'Period length',
    cycle_trend_title: 'Cycle length trend',
    my_last_cycles: 'My last cycles',
    did_you_know: 'Did you know?',
    cycle_tip_text: 'A normal cycle lasts between 21 and 35 days. Tap any day to record the start of your period.',
    cycle_settings_title: 'Cycle settings',
    cycle_length_label: 'Cycle length (days)',
    period_length_label: 'Period length (days)',
    period_start_label: 'Start:',
    period_word_short: 'Period',

    // Symptoms
    mood_happy: 'Good',
    mood_neutral: 'Neutral',
    mood_sad: 'Sad',
    mood_anxious: 'Anxious',
    mood_energetic: 'Energetic',
    my_journal: 'My journal',
    edit_label: 'Edit',
    journal_tab: 'Journal',
    history_tab: 'History',
    how_do_you_feel: 'How are you feeling?',
    feeling_today: '{mood}  You feel {label} today',
    pains_title: 'Pain',
    has_pain: 'I have pain',
    no_pain: 'No pain',
    intensity_label: 'Intensity',
    pain_mild: 'Mild',
    pain_unbearable: 'Unbearable',
    energy_level: 'Energy level',
    fatigue_label: 'Fatigue',
    fatigue_exhausted: 'Exhausted',
    fatigue_energetic: 'Full of energy',
    notes_facultative: 'Notes (optional)',
    notes_symptom_placeholder: 'Describe how you feel, any particular symptoms...',
    missing_mood_title: 'Missing mood',
    missing_mood_msg: 'Select your mood for today before saving.',
    save_error: 'Could not save. Please try again.',
    saved_exclaim: 'Saved!',
    update_action: 'Update',
    save_action: 'Save',
    symptom_tip_text: 'Keeping a regular journal helps identify patterns in your cycle and better understand your body.',
    no_symptom_history: 'No symptoms recorded yet. Your history for the last 14 days will appear here.',
    pain_intensity_short: 'Pain {n}/10',
    no_pain_short: 'No pain',
    fatigue_short: 'Fatigue {n}/10',

    // ShareCycle
    status_pending: 'Pending',
    status_active: 'Active',
    status_revoked: 'Revoked',
    code_label: 'Code',
    created_on: 'Created on {date}',
    partner_label: 'Partner: {name}',
    share_code_action: 'Share code',
    revoke_action: 'Revoke',
    share_join_message: 'Join me on LUNELA! My cycle-sharing code: {code}',
    share_join_title: 'LUNELA cycle sharing',
    load_shares_error: 'Could not load shares. Check your connection.',
    existing_link_title: 'Existing link',
    existing_link_msg: 'You already have an active or pending share. Revoke it before creating a new one.',
    default_user_name: 'User',
    create_share_error: 'Could not create the share. Please try again.',
    revoke_share_title: 'Revoke share',
    revoke_active_msg: 'Your partner will no longer be able to see your cycle. This action is irreversible.',
    revoke_pending_msg: 'This invite code will be cancelled.',
    revoke_error: 'Could not revoke. Please try again.',
    how_it_works: 'How does it work?',
    share_cycle_explain: 'Generate an invite code and share it with your partner. They will be able to see your cycle info on their Male profile. You can revoke access at any time.',
    revocable_access: 'Revocable access',
    limited_info: 'Limited info',
    secure_data: 'Secure data',
    generate_invite_code: 'Generate an invite code',
    current_share: 'Current share',
    no_active_share: 'No active share',
    history_label: 'History',
    no_share_title: 'No share',
    no_share_desc: 'Generate a code to let your partner see your cycle.',

    // Education
    nav_education: 'Education',
    education_subtitle: 'Learn about your body',
    no_content_category: 'No content in this category yet.',
    content_validated_note: 'Content validated by health professionals',
    article_educational_note: 'This information is educational. For any personal question, consult a health professional via Chat.',

    // Boy Health
    my_health: 'My Health',
    daily_tracking: 'Daily check-in',
    mood_label: 'Mood',
    stress_label: 'Stress',
    energy_label: 'Energy',
    notes_optional_placeholder: 'Notes (optional)...',
    trends_7d: 'Trends (last 7 days)',
    specialist_chat: 'Specialist Chat',
    specialist_chat_sub: 'Ask your questions confidentially',
    my_body: 'My body',
    no_data: 'No data',
    health_tip_text: 'Log your data every day to better understand the impact of stress and sleep on your wellbeing.',
    personal_question_note: 'For any personal question, consult a professional via Chat.',

    // UnderstandCycle
    understand_cycle_title: 'Understand the Cycle',
    understand_cycle_sub: 'To better support and be there',
    understand_cycle_intro: 'Understanding the menstrual cycle helps you be a better partner, brother, or friend. Tap each phase to learn more.',
    four_phases: 'The 4 phases',
    test_knowledge: 'Test your knowledge!',
    quiz_badges_sub: 'Take the quiz and earn badges',
    myths_realities: 'Myths & Facts',
    myth_label: 'MYTH',
    reality_label: 'FACT',
    go_further: 'Go further',
    understand_cycle_tip: 'Every woman experiences her cycle differently. Dialogue and listening are the best ways to understand what your partner is feeling.',

    // Quiz
    points_label: 'Points',
    quizzes_done_label: 'Quizzes done',
    streak_label: 'Streak 🔥',
    badges_count: 'Badges: {n} / {total}',
    quiz_tab: 'Quiz',
    badges_tab: 'Badges',
    choose_category: 'Choose a category',
    your_badges: 'Your badges',
    questions_count: '{n} questions',
    completed_label: 'Completed',
    validate_action: 'Confirm',
    see_results: 'See results',
    next_question: 'Next question',
    perfect_score: 'Perfect score!',
    good_job: 'Great job!',
    keep_learning: 'Keep learning!',
    new_badges_title: '🏅 New badges!',
    replay_action: 'Replay',
    back_to_quizzes: 'Back to quizzes',

    // Partner
    phase_menstruation: 'Menstruation',
    phase_follicular: 'Follicular phase',
    phase_ovulation: 'Ovulation',
    phase_luteal: 'Luteal phase',
    phase_tip_menstruation: 'Period phase. She may feel cramps or fatigue.',
    phase_tip_follicular: 'Energy is rising. Good time for activities together.',
    phase_tip_ovulation: 'Fertile period. Mood is generally positive.',
    phase_tip_luteal: 'Possible PMS toward the end of this phase. Be attentive to her wellbeing.',
    weekday_mon: 'Mo', weekday_tue: 'Tu', weekday_wed: 'We', weekday_thu: 'Th',
    weekday_fri: 'Fr', weekday_sat: 'Sa', weekday_sun: 'Su',
    period_legend: 'Period',
    fertile_legend: 'Fertile',
    cycle_legend: 'Cycle',
    partner_tip1: 'Ask how she feels without expecting a precise answer.',
    partner_tip2: 'A warm tea or hot water bottle can ease cramps.',
    partner_tip3: 'A short walk together can improve mood during PMS.',
    partner_tip4: 'Suggesting a movie or a calm activity during her period is always appreciated.',
    partner_tip5: 'Be patient: mood swings are hormonal, not personal.',
    partner_mode_title: 'Partner Mode',
    partner_mode_sub: 'Connect with your partner to better understand her cycle and be there for her.',
    enter_partner_code: "Enter your partner's code",
    enter_partner_code_sub: 'She generates this code from her LUNELA app → My Cycle → 👥',
    code_placeholder: 'E.G.: AB3X7K',
    code_too_short: 'Code too short.',
    code_not_found: 'Code not found or already used.',
    cant_use_own_code: "You can't use your own code.",
    network_error_retry: 'Network error. Please try again.',
    connect_action: 'Connect',
    why_use_mode: 'Why use this mode?',
    why_tip1: 'See her cycle and anticipate difficult periods',
    why_tip2: 'Get personalized advice based on her phase',
    why_tip3: 'Understand better to support better',
    connected_label: 'Connected',
    unlink_action: 'Unlink',
    unlink_title: 'Unlink partner',
    unlink_msg: 'You will no longer have access to her cycle. Confirm?',
    cycle_day_label: 'Day {n} of cycle',
    next_period_label: 'Next period',
    empathy_tip_of_day: 'Empathy tip of the day',
    partner_cycle_calendar: 'Her cycle calendar',
    recent_history: 'Recent history',
    period_from_date: 'Period from {date}',
    duration_days: 'Duration: {n} days',
    partner_no_data: 'Your partner hasn\'t recorded a cycle yet. Check back later.',
    recent_symptoms_14d: '💊 Recent symptoms (14 days)',
    next_tip: 'Next tip',
    close_action: 'Close',
    default_partner_name: 'Your partner',

    // Responsibility (UI chrome only — long-form content stays French)
    tab_contraception: 'Contraception',
    tab_consent: 'Consent',
    tab_planning: 'Planning',
    contra_intro_title: 'Contraception: a shared responsibility',
    contra_intro_text: 'Knowing all the methods lets you have an open conversation and make decisions together.',
    advantages_label: '✅ Advantages',
    attention_points_label: '⚠️ Points to consider',
    how_it_works_label: '📋 How it works',
    no_ist_protection_warning: "This method doesn't protect against STIs/HIV. Use a condom in addition if you're not in an exclusive, tested relationship.",
    important_reminder_label: 'Important reminder:',
    important_reminder_text: 'Only condoms protect simultaneously against unwanted pregnancy and STIs. "Double protection" (condom + another method) is the safest combination.',
    consent_hero_title: 'Informed consent',
    consent_hero_sub: 'Understanding and respecting consent is the basis of any healthy relationship. It is not optional, it is fundamental.',
    fries_principles_title: 'The 5 FRIES principles',
    red_flags_title: 'Behaviors to never adopt',
    how_to_talk_consent: 'How to talk about consent?',
    consent_note_text: "Asking these questions isn't awkward — it's a sign of respect and maturity that strengthens trust in the relationship.",
    planning_hero_title: 'Family planning',
    planning_hero_sub: 'The decision to have a child is one of the most important in life. It is made together, with communication and preparation.',
    planning_topics_title: 'Essential topics to discuss together',
    ist_screening_label: 'STI screening:',
    ist_screening_text: 'Before stopping barrier contraception, it is recommended that both partners get a full STI screening. It is an act of mutual respect, not distrust.',
    useful_resources_title: 'Useful resources',

    // Onboarding
    onboard_title_1: 'Welcome to\nLUNELA',
    onboard_sub_1: 'Your intimate and reproductive health companion. Made with care for everyone.',
    onboard_title_2: 'Track your\ncycle',
    onboard_sub_2: 'Record your periods, view your cycle on a colorful calendar, and anticipate every phase.',
    onboard_title_3: 'Chat with\nspecialists',
    onboard_sub_3: 'Ask your questions confidentially to approved health professionals. Your identity stays anonymous.',
    onboard_title_4: 'Your data,\nyour rules',
    onboard_sub_4: 'Everything is encrypted and secure. You choose what you share, and with whom.',
    start_action: 'Get started',
    next_action: 'Next',
    skip_action: 'Skip',

    // SurveyGate
    gender_female: 'Female',
    gender_male: 'Male',
    gender_other: 'Other/Not specified',
    mandatory_label: 'Required',
    select_answer_required: 'Please select an answer.',
    select_gender_required: 'Please indicate your gender.',
    gender_not_specified: 'Not specified',
    save_response_error: 'Could not save your response. Check your connection.',
    mandatory_survey_badge: 'MANDATORY SURVEY',
    survey_intro_text: 'Please answer this survey to continue using LUNELA.',
    your_answer_label: 'Your answer',
    your_gender_label: 'Your gender',
    submit_answer: 'Submit my answer',
    survey_anon_note: 'Your response is anonymous and confidential.',

    // Contraceptives
    daily_reminder_title: 'Daily reminder',
    daily_reminder_sub: 'Get a reminder every day',
    reminder_time_label: 'Reminder time:',
    contraceptive_reminder_title: '💊 Contraceptive reminder',
    contraceptive_reminder_body: "Don't forget to take your contraceptive today.",
    contraceptives_title: 'Contraceptives & Protection',
    contraceptives_sub: 'Complete guide to contraceptive and protection methods',
    no_items_category: 'No items in this category',
    contraceptives_disclaimer: 'This information is educational. Consult a health professional for advice suited to you.',
    efficacy_label: 'Efficacy',
    duration_label: 'Duration',
    advantages_short: '✅ Advantages',
    disadvantages_short: '⚠️ Disadvantages',

    // Chat
    anonymous_label: 'Anonymous',
    message_not_sent: 'Message not sent. Check your connection.',
    you_appear_as: 'You appear as: ',
    available_specialists: 'Available specialists',
    no_specialist_available: 'No specialist available\nat the moment',
    online_label: 'Online',
    offline_label: 'Offline',
    health_specialist_default: 'Health specialist',
    you_prefix: 'You: ',
    confidentiality_guaranteed: 'Confidentiality guaranteed',
    confidentiality_text: 'Your real identity is never revealed to specialists.',
    start_conversation: 'Start the conversation.\nYou are anonymous.',
    message_placeholder: 'Your message...',
    new_patient_message: '💬 New patient message',
    chat_screen_sub: 'Chat confidentially',

    // Forum
    specialist_professional_label: 'Health professional',
    just_now: 'Just now',
    minutes_ago: '{n} min ago',
    hours_ago: '{n}h ago',
    thanks_label: 'Thank you',
    report_transmitted: 'Your report has been sent to moderation.',
    report_send_error: 'Could not send the report.',
    report_content_title: 'Report this content',
    report_content_why: 'Why are you reporting this content?',
    send_report_action: 'Send report',
    discussion_default: 'Discussion',
    reply_send_error: 'Could not send the reply.',
    be_first_to_reply: 'Be the first to reply',
    reply_placeholder: 'Your reply...',
    forum_title: 'Anonymous Forum',
    post_action: 'Post',
    specialist_reply_note: 'Your replies are marked as coming from a health professional.',
    no_discussion_yet: 'No discussion yet',
    publish_post_error: 'Could not publish.',
    new_discussion_title: 'New discussion',
    question_title_placeholder: 'Title of your question...',
    describe_situation_placeholder: 'Describe your situation...',
    publish_anonymously: 'Publish anonymously',

    // VerifyEmail
    not_yet_verified_title: 'Not verified yet',
    not_yet_verified_msg: 'Open your mailbox, find the LUNELA email and click the confirmation link. Then come back here.',
    network_error_title: 'Network error',
    network_error_msg: 'Check your internet connection.',
    email_sent_title: 'Email sent',
    email_sent_msg: 'A new verification email was sent to {email}',
    resend_email_error: 'Could not send the email. Try again later.',
    verify_email_title: 'Verify your email',
    verify_email_sub: 'A confirmation link has been sent to your email address.',
    verify_step1: 'Open your mailbox',
    verify_step2: 'Find the LUNELA email',
    verify_step3: 'Click the confirmation link',
    verify_step4: 'Come back here and tap the button below',
    confirmed_email_action: 'I confirmed my email',
    resend_in_seconds: 'Resend in {n}s',
    resend_email_action: 'Resend email',
    spam_notice: 'Remember to check your spam / junk folder',
    logout_action: 'Log out',

    // PendingApproval
    pending_request_title: 'Request pending',
    pending_admin_sub: 'Your administrator account request is being reviewed by an existing administrator.',
    pending_specialist_sub: 'Your specialist account request is being reviewed by our administration team.',
    status_label: 'Status:',
    pending_status: 'Pending',
    check_status_action: 'Check status',

    // AdminRegister / SpecialistRegister
    fill_all_fields: 'Please fill in all fields.',
    passwords_mismatch: 'Passwords do not match.',
    password_too_short: 'Password too short (min. 6 characters).',
    admin_account_title: 'Administrator Account',
    first_admin_note: 'First administrator — Account automatically approved',
    admin_pending_note: 'Your account will be validated by an existing administrator',
    full_name_label: 'Full name',
    email_address_label: 'Email address',
    password_label: 'Password',
    confirm_password_label: 'Confirm password',
    min_6_chars_placeholder: 'Minimum 6 characters',
    retype_password_placeholder: 'Retype your password',
    create_account_action: 'Create account',
    fill_required_fields: 'Please fill in all required fields.',
    specialist_account_title: 'Specialist Account',
    specialist_pending_note: 'Your request will be reviewed and approved by our administration team.',
    full_name_required: 'Full name *',
    email_required: 'Email *',
    speciality_required: 'Speciality *',
    credentials_label: 'Diplomas / License number *',
    credentials_placeholder: 'E.g.: Medical doctorate - License No. 12345',
    institution_label: 'Institution / Facility',
    institution_placeholder: 'Hospital / Clinic / Office',
    professional_phone_label: 'Professional phone',
    password_required: 'Password *',
    confirm_password_required: 'Confirm password *',
    submit_request_action: 'Submit my request',

    // AdminDashboard
    live_updated: 'Live · Updated {time}',
    greeting_hello: 'Hello 👋',
    admin_default_name: 'Administrator',
    admin_role_badge: 'LUNELA Administrator',
    pending_specialist_approval: '⚠️ {n} pending approval',
    approved_count: '{n} approved',
    active_of_total_surveys: '{active} active · {total} total',
    pending_count: '⚠️ {n} pending',
    active_count: '{n} active',
    manage_contraceptive_methods: 'Manage contraceptive methods',
    pending_reports_count: '⚠️ {n} pending report(s)',
    no_pending_reports: 'No pending reports',
    elements_pending_action: '{n} item{s} pending action',
    overview_title: 'Overview',
    users_group_label: '👥 Users',
    total_label: 'Total',
    women_label: 'Women',
    men_label: 'Men',
    specialists_group_label: '🩺 Specialists',
    approved_label: 'Approved',
    pending_label: 'Pending',
    blocked_label: 'Blocked',
    platform_group_label: '📊 Platform',
    active_surveys_label: 'Active surveys',
    total_surveys_label: 'Total surveys',
    admins_pending_label: 'Admins pending',
    analytics_title: 'Analytics',
    users_distribution: 'User distribution',
    total_word: 'total',
    others_label: 'Others',
    specialists_status: 'Specialist status',
    platform_label: 'Platform',
    active_admins_label: 'Active admins',
    approved_specialists_label: 'Approved specialists',
    management_title: 'Management',
    create_new_survey: 'Create a new survey',
    view_survey_reports: 'View survey reports',
    specialists_label: 'Specialists',
    surveys_label: 'Surveys',
    administrators_label: 'Administrators',
    contraceptives_label: 'Contraceptives',
    forum_moderation_label: 'Forum Moderation',

    // SpecialistApproval
    specialist_management_title: 'Specialist Management',
    action_approve: 'approve',
    action_block: 'block',
    action_reset_pending: 'reset to pending',
    confirm_title: 'Confirm',
    confirm_action_person: 'Do you want to {action} Dr. {name}?',
    success_title: '✅ Success',
    status_updated: 'Status updated: {status}',
    update_failed: 'Update failed: {error}',
    load_error_prefix: 'Error: {error}',
    specialists_load_error: 'Could not load specialists.\n{error}',
    loading_impossible: 'Loading failed',
    retry_action: 'Retry',
    no_specialists_category: 'No specialists in this category',
    pull_to_refresh_hint: 'Pull down to refresh',
    approve_action: 'Approve',
    reject_action: 'Reject',
    block_action: 'Block',
    unblock_action: 'Unblock',

    // AdminManagement
    approve_or_reject_admin: '{action} the admin account of {name}?',
    first_admin_auto_note: 'The first administrator is created automatically. Subsequent ones require your approval.',
    no_admin_category: 'No administrators in this category',
    first_admin_badge: '⭐ First Admin',
    you_label: '👑 You',

    // ForumModeration
    action_impossible: 'Action failed.',
    delete_content_title: 'Delete this content',
    delete_reply_msg: 'This reply will be permanently deleted from the forum.',
    delete_discussion_msg: 'This discussion and all its replies will be permanently deleted.',
    delete_action: 'Delete',
    delete_impossible: 'Deletion failed.',
    reported_reply: 'Reported reply',
    reported_discussion: 'Reported discussion',
    empty_content_label: '(empty content)',
    forum_clean_note: 'The forum is clean for now.',

    // ContraceptivesManager
    delete_confirm_name: 'Delete "{name}"?',
    delete_failed: 'Deletion failed.',
    name_required: 'Name is required.',
    save_failed: 'Save failed.',
    no_item: 'No item',
    edit_action: 'Edit',
    add_item_action: 'Add an item',
    change_action: 'Change',
    color_label: 'Color',
    name_required_label: 'Name *',
    category_label: 'Category',
    efficacy_field_label: 'Efficacy',
    duration_field_label: 'Duration',
    description_label: 'Description',
    description_placeholder: 'Method description...',
    advantages_max3: 'Advantages (3 max)',
    advantage_n: 'Advantage {n}',
    disadvantages_max3: 'Disadvantages (3 max)',
    disadvantage_n: 'Disadvantage {n}',
    choose_emoji: 'Choose an emoji',

    // SurveyManager
    disable_mandatory_confirm: 'Disable the mandatory answer requirement?',
    make_mandatory_confirm: '⚠️ Make this survey MANDATORY? Users will have to answer it before using the app.',
    delete_survey_confirm: 'Permanently delete "{title}"?',
    create_action: 'Create',
    no_survey_created: 'No survey created',
    create_first_survey: 'Create the first survey',
    mandatory_badge: 'MANDATORY',
    closed_badge: 'CLOSED',
    options_count: '{n} options',
    responses_count: '{n} responses',
    public_label: 'Public',
    private_label: 'Private',
    active_toggle: '● Active',
    inactive_toggle: '○ Inactive',
    mandatory_toggle: 'Mandatory',
    optional_toggle: '○ Optional',
    report_label: 'Report',

    // CreateSurvey
    max_8_options: 'Maximum 8 options',
    min_2_options: 'Minimum 2 options',
    enter_title_error: 'Please enter a title.',
    enter_question_error: 'Please enter the question.',
    min_2_options_error: 'Minimum 2 answer options.',
    survey_created_title: '✅ Survey created',
    survey_created_mandatory_msg: 'The survey is mandatory — users will have to answer it.',
    survey_created_active_msg: 'The survey is now active.',
    create_survey_error: 'Could not create the survey.',
    new_survey_title: 'New Survey',
    survey_title_label: 'Survey title *',
    survey_title_placeholder: 'E.g.: LUNELA service satisfaction',
    question_asked_label: 'Question asked *',
    question_placeholder: 'Ask your question here...',
    response_options_label: 'Answer options *',
    option_n: 'Option {letter}',
    add_option_action: '+ Add an option',
    settings_title: '⚙️ Settings',
    mandatory_survey_label: '⚡ Mandatory survey',
    mandatory_survey_desc: 'Users must answer to continue',
    public_survey_label: '🌍 Public survey',
    public_survey_desc: 'Visible to all users',
    ask_gender_label: '👤 Ask for gender',
    ask_gender_desc: 'Each respondent provides their gender',
    mandatory_survey_warning: "⚡ This survey will be shown to all active users and will block access to the app until answered.",
    creating_ellipsis: 'Creating...',
    launch_survey_action: '🚀 Launch survey',

    // SurveyReport
    survey_report_title: 'Survey Report',
    total_responses: '👥 {n} responses',
    results_by_answer: 'Results by answer',
    gender_breakdown_title: 'Gender breakdown',
    no_response_yet: 'No response yet',
    export_report_action: 'Export report',
    report_survey_prefix: 'LUNELA SURVEY REPORT',
    report_title_field: 'Title',
    report_question_field: 'Question',
    report_total_responses_field: 'Total responses',
    report_by_answer: 'BY ANSWER:',
    report_by_gender: 'BY GENDER:',
    report_share_title: 'Report - {title}',
    not_specified_short: 'Not specified',

    // SpecialistDashboard
    patient_default: 'Patient',
    dossier_label: 'Record',
    no_message_yet: 'No message yet',
    professional_response_placeholder: 'Your professional response...',
    message_not_sent_short: 'Message not sent.',
    new_reply_notification: '💬 Reply from {name}',
    default_specialist: 'Specialist',
    default_specialist_short: 'your specialist',
    conversations_title: 'Conversations',
    urgent_count_label: '{n} urgent{s}',
    all_count: 'All ({n})',
    urgent_only_count: 'Urgent ({n})',
    no_urgent_conv: 'No urgent conversation',
    no_conversation: 'No conversation',
    all_conv_uptodate: 'All conversations are up to date ✅',
    patients_appear_here: 'Patients who contact you will appear here',
    urgent_flag: 'URGENT',
    start_conv_placeholder: 'Start the conversation...',
    stats_title: 'Statistics',
    kpi_conversations: 'Conversations',
    kpi_messages_received: 'Messages received',
    kpi_unread: 'Unread',
    kpi_response_rate: 'Response rate',
    kpi_avg_msgs: 'Avg. msgs/conv',
    kpi_answered_conv: 'Answered conv.',
    activity_7d_title: 'Activity — last 7 days',
    no_activity_recorded: 'No activity recorded',
    patient_distribution: 'Patient distribution',
    patients_word: 'patients',
    exchange_quality: 'Exchange quality',
    total_conv_short: 'Total conv.',
    answered_short: 'Answered',
    unread_short: 'Unread',
    avg_msgs_short: 'Avg. msgs',
    professional_profile: 'Professional profile',
    speciality_field: 'Speciality',
    institution_field: 'Institution',
    phone_field: 'Phone',
    diplomas_field: 'Diplomas',
    status_field: 'Status',
    approved_check: 'Approved ✅',
    professional_resources: 'Professional resources',
    greeting_hello_comma: 'Hello,',
    urgent_conversations_count: '{n} urgent conversation{s}',
    messages_awaiting_reply: '{n} message{s} awaiting reply',
    conversations_stat: 'Conversations',
    unread_stat: 'Unread',
    messages_stat: 'Messages',
    conversations_count_label: '{n} patient{s}',
    none_label: 'None',
    overview_label: 'Overview',
    resources_sub: 'Protocols, tools, training',
    anonymous_forum_label: 'Anonymous Forum',
    follow_exchanges_sub: 'Follow discussions and reply',
    priority_treatment: 'Priority attention needed',
    recent_label: 'Recent',
    profile_female_label: 'Female profile',
    profile_male_label: 'Male profile',
    health_worker_label: 'Healthcare worker',
    resources_label: 'Resources',

    // ResourcesScreen
    cat_all: 'All',
    cat_protocols: 'Protocols',
    cat_guidelines: 'Guidelines',
    cat_articles: 'Articles',
    cat_tools: 'Tools',
    cat_formations: 'Training',
    cat_contacts: 'Contacts',
    link_label: 'Link',
    added_by: 'Added by {name}',
    open_link_error: 'Could not open this link.',
    keywords_label: 'Keywords',
    access_label: 'Access',
    call_number: 'Call {number}',
    open_link_action: 'Open link',
    source_label: 'Source: {source}',
    lunela_base: 'LUNELA Database',
    required_fields_title: 'Required fields',
    required_fields_msg: 'Title and description are required.',
    save_resource_error: 'Could not save. Check your connection.',
    add_resource_title: 'Add a resource',
    publish_action: 'Publish',
    title_required_label: 'Title *',
    title_placeholder: 'E.g.: STI Protocol – course of action',
    description_required_label: 'Description *',
    describe_resource_placeholder: 'Describe the resource in detail...',
    url_optional_label: 'URL link (optional)',
    tags_label: 'Tags (comma separated)',
    resource_visibility_note: 'The resource will be visible to all specialists connected to LUNELA after publishing.',
    search_resource_placeholder: 'Search for a resource...',
    resource_count: '{n} resource{s}',
    no_result_title: 'No results',
    no_result_search: 'No resource matches "{search}"',
    no_result_category: 'No resource in this category.',
    add_first_resource: 'Add the first resource',
    add_action: 'Add',

    // PatientDataSheet
    most_recent_label: 'Most recent',
    patient_record_title: 'Patient record',
    symptoms_tab: 'Symptoms',
    cycles_tab: 'Cycles',
    loading_record: 'Loading record...',
    born_on: 'Born on {date}',
    cycle_approx: 'Cycle ~{n}d',
    symptoms_14d_title: '📋 Symptoms — last 14 days',
    no_symptom_14d: 'No symptoms recorded in the last 14 days.',
    last_5_cycles_title: '🌙 Last 5 cycles',
    no_cycle_recorded: 'No cycle recorded.',
    avg_duration_label: 'Avg. duration',
    cycles_recorded_label: 'Cycles recorded',
    default_patient_label: 'Patient',

    // QuizManager
    quiz_manager_title: 'Quiz Management',
    add_question_action: 'Add a question',
    question_text_label: 'Question *',
    question_text_placeholder: 'E.g.: How many days does a cycle last?',
    option_n_label: 'Option {n}',
    correct_answer_label: 'Correct answer',
    explanation_label: 'Explanation',
    explanation_placeholder: 'Explain the correct answer...',
    topic_label: 'Category',
    question_required: 'The question and all 4 options are required.',
    select_correct_answer: 'Select the correct answer.',
    no_question: 'No question',
    delete_confirm_question: 'Delete this question?',
    tap_option_to_mark_correct: 'Tap an option to mark it as the correct answer.',
    manage_quiz_questions: 'Manage quiz questions',

    // EducationManager
    education_manager_title: 'Education Content Management',
    manage_education_content: 'Manage educational articles',
    add_article_action: 'Add an article',
    article_title_label: 'Title *',
    article_title_placeholder: 'E.g.: The 4 phases of the menstrual cycle',
    article_body_label: 'Content *',
    article_body_placeholder: 'Write the article content...',
    target_profile_label: 'Target audience',
    article_required: 'Title and content are required.',
    no_article: 'No article',
    delete_confirm_article: 'Delete this article?',

    // Dual-role account (girl/boy + specialist)
    nav_become_specialist: 'Become a specialist',
    nav_specialist_pending: 'Application pending',
    nav_specialist_space: 'Specialist space',
    become_specialist_intro: "Fill out this form to submit your application. An administrator will review your professional profile.",
    specialist_application_pending_title: 'Application under review',
    specialist_application_pending_sub: "Your specialist application is being reviewed by an administrator. You'll be notified once it's approved.",
    application_submitted_title: 'Application sent',
    application_submitted_msg: 'Your application has been submitted.',
  },
};

const LanguageContext = createContext({
  lang: 'fr',
  t: (key) => TRANSLATIONS.fr[key] ?? key,
  setLang: () => {},
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('fr');

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then(v => { if (v === 'en') setLangState('en'); });
  }, []);

  const setLang = useCallback(async (l) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l).catch(() => {});
  }, []);

  // params : remplace les {placeholder} dans la chaîne, ex. t('greet', { name: 'Awa' })
  const t = useCallback((key, params) => {
    let str = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.fr[key] ?? key;
    if (params) {
      Object.keys(params).forEach(k => { str = str.replace(`{${k}}`, params[k]); });
    }
    return str;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
